//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmoonYarWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Azmoon
    {
        public Azmoon()
        {
            this.Mapping_Profile_Azmoon = new HashSet<Mapping_Profile_Azmoon>();
            this.Soalats = new HashSet<Soalat>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDateOnUtc { get; set; }
        public string F_UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> StartDateOnUtc { get; set; }
        public Nullable<System.DateTime> EndDateOnUtc { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Mapping_Profile_Azmoon> Mapping_Profile_Azmoon { get; set; }
        public virtual ICollection<Soalat> Soalats { get; set; }
    }
}
