//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmoonYarWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mapping_Profile_Azmoon> Mapping_Profile_Azmoon { get; set; }
        public virtual DbSet<Mapping_Profile_Pasokh> Mapping_Profile_Pasokh { get; set; }
        public virtual DbSet<Pasokh> Pasokhs { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Soalat> Soalats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Azmoon> Azmoons { get; set; }
    }
}
