//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmoonYarWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasokh
    {
        public Pasokh()
        {
            this.Mapping_Profile_Pasokh = new HashSet<Mapping_Profile_Pasokh>();
        }
    
        public int Id { get; set; }
        public string AnswerText { get; set; }
        public Nullable<int> AnswerKey { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> F_SoalatId { get; set; }
        public Nullable<System.DateTime> EditDateOnUtc { get; set; }
    
        public virtual ICollection<Mapping_Profile_Pasokh> Mapping_Profile_Pasokh { get; set; }
        public virtual Soalat Soalat { get; set; }
    }
}
