//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmoonYarWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Mapping_Profile_Azmoon = new HashSet<Mapping_Profile_Azmoon>();
            this.Mapping_Profile_Pasokh = new HashSet<Mapping_Profile_Pasokh>();
        }
    
        public int Id { get; set; }
        public string Tell { get; set; }
        public string CodeMelli { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreateDateOnUtc { get; set; }
        public Nullable<System.DateTime> EditDateOnUtc { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Mapping_Profile_Azmoon> Mapping_Profile_Azmoon { get; set; }
        public virtual ICollection<Mapping_Profile_Pasokh> Mapping_Profile_Pasokh { get; set; }
    }
}
