//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmoonYarWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soalat
    {
        public Soalat()
        {
            this.Pasokhs = new HashSet<Pasokh>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> CreateDateOnUtc { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> F_AzmoonId { get; set; }
        public Nullable<int> Pasokh { get; set; }
        public Nullable<int> SoalNumber { get; set; }
    
        public virtual ICollection<Pasokh> Pasokhs { get; set; }
        public virtual Azmoon Azmoon { get; set; }
    }
}
